---
title: "A3: Incarceration"
output: html_document
---

### Introduction

An introduction of the problem domain and a description of the variable(s) you are choosing to analyze (and why!)

### Summary Information

Write a summary paragraph of findings that includes the 5 values calculated from your summary information R script

These will likely be calculated using your DPLYR skills, answering questions such as: 

- What is the average value of my variable across all the counties (in the current year)?
- Where is my variable the highest / lowest?
- How much has my variable change over the last N years?

Feel free to calculate and report values that you find relevant. Again, remember that the purpose is to think about how these measure of incarceration vary by race.

### The Dataset

This particular dataset provides information about prison populations by county 
and state within the United States. The data was collected by the Vera Institute 
to expose patterns of inequality in incarceration data. The data was collected 
by compiling information from the Bureau of Justice Statistics (BJS) data 
collections. There are 153811 rows and 36 columns in the dataset which is quite 
large considering that this is only a portion of the real dataset. There are 
definitely some questions of power that need to be addressed when working with 
data that can be sensitive. It is the programmers responsibility to use this 
data to contribute to the general knowledge about this population. Data should 
not be used to push a personal narrative or agenda especially one that is harmful 
to others. Finally, it is important to note that there are some possible 
limitations with this data such as the number of missing data from the table 
musically for certain race categories. Without this data it is difficult to 
evaluate the accuracy of the provided visualizations and data summaries. This is 
not to say that this is not a credible source of information but rather 
something that has faults and should not always be taken at face value. Context 
is as important as the numerical data itself. 


### Trends Over Time Chart

This visualization displays the total prison population for the top 5 largest 
counties (in 2018) over the course of 5 years. Since this database lacks
information for prison population past 2016, it seemed more interesting to only
include valid values. This chart is included because it encompasses the most
recent data as described by the data frame. An interesting pattern that emerged
was that Harris County, GA surpassed Maricopa County, AZ in prison population
after 2014.

``````{r, echo = FALSE, warning = FALSE, message = FALSE, code = readLines("trends_over_time.R")}
```

### Variable Comparison Chart

Include a chart. Make sure to describe why you included the chart, and what patterns emerged

The second chart that you will create and include will show how two different (continuous) variables are related to one another. Again, think carefully about what such a comparison means and what you want to communicate to your user (you may have to find relevant trends in the dataset first!). Here are some requirements to help guide your design:

- You must have clear x and y axis labels
- The chart needs a clear title 
- If you choose to add a color encoding (not required), you need a legend for your different color and a clear legend title

### Map

Include a chart. Make sure to describe why you included the chart, and what patterns emerged

The last chart that you will create and include will show how a variable is distributed geographically. Again, think carefully about what such a comparison means and what you want to communicate to your user (you may have to find relevant trends in the dataset first!). Here are some requirements to help guide your design:

- Your map needs a title
- Your color scale needs a legend with a clear label
- Use a map based coordinate system to set the aspect ratio of your map

